=== abaldeweg/ui/packages/@baldeweg/ui/src/components/component.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "component.schema.json",
  "title": "Component",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "props": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "type": {
            "type": "array",
            "items": {
              "enum": [
                "String",
                "Number",
                "Boolean",
                "Array",
                "Object",
                "Date",
                "Function",
                "Symbol"
              ]
            }
          },
          "allowedValues": {
            "type": "array",
            "items": {
              "type": "string",
              "uniqueItems": true
            }
          },
          "default": {
            "type": [
              "string",
              "boolean"
            ]
          }
        },
        "required": [
          "name",
          "type"
        ]
      }
    },
    "slots": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "default": "default"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "default": "click"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "required": [
      "name"
    ]
  }
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BEditor/BEditor.json
{
  "$schema": "./../component.schema.json",
  "name": "BEditor",
  "description": "Additional attributes are passed to the underlying editor.",
  "props": [
    {
      "name": "modelValue",
      "type": [
        "String"
      ]
    },
    {
      "name": "name",
      "type": [
        "String"
      ]
    },
    {
      "name": "id",
      "type": [
        "String"
      ]
    },
    {
      "name": "label",
      "type": [
        "String"
      ]
    },
    {
      "name": "hideLabel",
      "type": [
        "Boolean"
      ],
      "default": false
    },
    {
      "name": "help",
      "type": [
        "String"
      ]
    },
    {
      "name": "language",
      "type": [
        "String"
      ],
      "default": "json"
    }
  ],
  "events": [
    {
      "name": "update:modelValue"
    }
  ]
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BModal/BModal.json
{
  "$schema": "./../component.schema.json",
  "name": "BModal",
  "description": "If you use a form, consider wrapping the modal with it.",
  "props": [
    {
      "name": "modelValue",
      "type": [
        "Boolean"
      ],
      "default": false
    },
    {
      "name": "width",
      "type": [
        "Number"
      ],
      "default": "600"
    },
    {
      "name": "closeButton",
      "type": [
        "Boolean"
      ],
      "default": true
    }
  ],
  "slots": [
    {
      "name": "title"
    },
    {
      "name": "default"
    },
    {
      "name": "footer"
    }
  ],
  "events": [
    {
      "name": "update:modelValue"
    }
  ]
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BButton/BButton.json
{
  "$schema": "./../component.schema.json",
  "name": "BButton",
  "props": [
    {
      "name": "design",
      "type": [
        "String"
      ],
      "default": "primary",
      "allowedValues": [
        "primary",
        "primary_danger",
        "primary_wide",
        "outline",
        "outline_danger",
        "outline_wide",
        "text",
        "text_danger"
      ]
    },
    {
      "name": "ripple",
      "type": [
        "Boolean"
      ],
      "default": false
    }
  ],
  "slots": [
    {
      "name": "default"
    }
  ],
  "events": [
    {
      "name": "click"
    }
  ]
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BSelect/BSelect.json
{
  "$schema": "./../component.schema.json",
  "name": "BSelect",
  "description": "Additional attributes are passed to the underlying input or select element.",
  "props": [
    {
      "name": "modelValue",
      "type": [
        "Array"
      ]
    },
    {
      "name": "type",
      "type": [
        "String"
      ],
      "default": "checkbox",
      "allowedValues": [
        "checkbox",
        "radio",
        "options"
      ]
    },
    {
      "name": "name",
      "type": [
        "String"
      ]
    },
    {
      "name": "id",
      "type": [
        "String"
      ]
    },
    {
      "name": "help",
      "type": [
        "String"
      ]
    },
    {
      "name": "options",
      "type": [
        "Object"
      ]
    }
  ],
  "events": [
    {
      "name": "update:modelValue"
    }
  ]
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BUpload/BUpload.json
{
  "$schema": "./../component.schema.json",
  "name": "BUpload",
  "description": "Set the enctype of the parent form to `enctype=\"multipart/form-data\"`.",
  "props": [
    {
      "name": "id",
      "type": [
        "String"
      ],
      "example": "upload"
    },
    {
      "name": "text",
      "type": [
        "String"
      ],
      "example": "Upload files"
    },
    {
      "name": "accept",
      "description": "Accepted file formats e.g. `image/jpeg, image/jpg, image/png, image/webp`",
      "type": [
        "String"
      ],
      "example": "image/jpeg, image/jpg, image/png, image/webp"
    }
  ],
  "events": [
    {
      "name": "update:modelValue"
    }
  ]
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BForm/BFormInput.json
{
  "$schema": "./../component.schema.json",
  "name": "BFormInput",
  "description": "Not applicable to checkbox and radio.",
  "props": [
    {
      "name": "modelValue",
      "type": [
        "String",
        "Number"
      ]
    },
    {
      "name": "noStyling",
      "type": [
        "Boolean"
      ],
      "default": false
    },
    {
      "name": "event",
      "type": [
        "Boolean"
      ],
      "default": false
    },
    {
      "name": "focus",
      "type": [
        "Boolean"
      ],
      "default": false
    }
  ],
  "events": [
    {
      "name": "update:modelValue"
    }
  ]
}

=== abaldeweg/ui/packages/@baldeweg/ui/src/components/BForm/BForm.json
{
  "$schema": "./../component.schema.json",
  "name": "BForm",
  "description": "The form component is just a wrapper, you have to assign classes to your elements. Please omit the `<form>` element itself.",
  "props": [
    {
      "name": "noMargin",
      "type": [
        "Boolean"
      ],
      "default": false
    }
  ],
  "slots": [
    {
      "name": "default"
    }
  ]
}
